name: Run Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-json-ctrf

    - name: Run tests
      #run: pytest -ctrf $REPORT -n $PROC --testomatio reportyyp
      run: pytest -ctrf $REPORT -n $PROC # --testomatio reportyyp
      env:
        REPORT: 'test-results/result.json'
        PROC: 'auto'
        TESTOMATIO: ${{secrets.TESTOMATIO_API_KEY}}
        TESTOMATIO_CODE_STYLE: 'pep8'
    
    - name: Generate Pretty Report
      if: always()
      run: |
        npx github-actions-ctrf test-results/report.json



